//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreVisits
    {
        public int ID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> EmployeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
