//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActor
    {
        public int ActorID { get; set; }
        public string ActorName { get; set; }
        public Nullable<System.DateTime> ActorDOB { get; set; }
        public string ActorGender { get; set; }
    }
}
