//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCast
    {
        public int CastID { get; set; }
        public Nullable<int> CastFilmID { get; set; }
        public Nullable<int> CastActorID { get; set; }
        public string CastCharacterName { get; set; }
    }
}
