//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDirector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDirector()
        {
            this.tblFilm = new HashSet<tblFilm>();
        }
    
        public int DirectorID { get; set; }
        public string DirectorName { get; set; }
        public Nullable<System.DateTime> DirectorDOB { get; set; }
        public string DirectorGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFilm> tblFilm { get; set; }
    }
}
