//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilm
    {
        public int FilmID { get; set; }
        public string FilmName { get; set; }
        public Nullable<System.DateTime> FilmReleaseDate { get; set; }
        public Nullable<int> FilmDirectorID { get; set; }
        public Nullable<int> FilmLanguageID { get; set; }
        public Nullable<int> FilmCountryID { get; set; }
        public Nullable<int> FilmStudioID { get; set; }
        public string FilmSynopsis { get; set; }
        public Nullable<int> FilmRunTimeMinutes { get; set; }
        public Nullable<long> FilmCertificateID { get; set; }
        public Nullable<int> FilmBudgetDollars { get; set; }
        public Nullable<int> FilmBoxOfficeDollars { get; set; }
        public Nullable<int> FilmOscarNominations { get; set; }
        public Nullable<int> FilmOscarWins { get; set; }
    
        public virtual tblCertificate tblCertificate { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblDirector tblDirector { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblStudio tblStudio { get; set; }
    }
}
