//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitesFrameworkDataAktarım
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFilmSimple
    {
        public int FilmID { get; set; }
        public string FilmName { get; set; }
        public Nullable<int> FilmBoxOfficeDollars { get; set; }
    }
}
